#!/usr/bin/env node
 
 const path = require('path');

 const CLIEngine = require('eslint').CLIEngine


 const engine = new CLIEngine({
 	configFile: path.join(__dirname, '..', '.eslintrc.js'),
 });

 const report = engine.executeOnFiles(['client/**/*.js', 'client/**/*.jsx']);
 const formatter = engine.getFormatter();

 console.log(formatter(report.results));

 if (report.errorCount !== 0) {
 	process.exit(1);
 }